config/routes.rb
Rails.application.routes.draw do

  namespace :admin do
    DashboardManifest::DASHBOARDS.each do |dashboard_resource|
      resources dashboard_resource
    end

    root controller: DashboardManifest::ROOT_DASHBOARD, action: :index
  end

  mount RailsAdmin::Engine => '/admin2', as: 'rails_admin'

  root to: 'visitors#index'

  devise_for :users

  get '/shops', to: 'shops#index'
  post '/shops/find', to: 'shops#find'

  # resources :users
end

app/models/location.rb
class Location < ActiveRecord::Base

  attr_accessor :lat, :lng, :address, :range, :number


  validate :address_or_coordinates
  validate :distance_or_best

  def address_or_coordinates
    unless ( lat.present? && lng.present? ) || address.present?
      errors.add(:lat, "can't be blank") if lat.blank?
      errors.add(:lng, "can't be blank") if lng.blank?
      errors.add(:address, "can't be blank") if address.blank?
    end
  end

  def distance_or_best
    unless number.present? || range.present?
      errors.add(:number, "can't be blank") if number.blank?
      errors.add(:range, "can't be blank") if range.blank?
    end
  end

end

app/models/shop.rb
class Shop < ActiveRecord::Base

  geocoded_by :full_street_address   # can also be an IP address
  after_validation :geocode          # auto-fetch coordinates

  reverse_geocoded_by :latitude, :longitude
  after_validation :reverse_geocode  # auto-fetch address

  def full_street_address
    "#{address}, #{city} #{zip}"
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  enum role: [:user, :vip, :admin]
  after_initialize :set_default_role, :if => :new_record?

  def set_default_role
    self.role ||= :user
  end

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/admin/application_controller.rb
# All Administrate controllers inherit from this `Admin::ApplicationController`,
# making it the ideal place to put authentication logic or other
# before_filters.
#
# If you want to add pagination or other controller-level concerns,
# you're free to overwrite the RESTful controller actions.
module Admin
  class ApplicationController < Administrate::ApplicationController
    before_filter :authenticate_admin

    def authenticate_admin
      # TODO Add authentication logic here.
    end

    # Override this value to specify the number of elements to display at a time
    # on index pages. Defaults to 20.
    # def records_per_page
    #   params[:per_page] || 20
    # end
  end
end

app/controllers/admin/shops_controller.rb
module Admin
  class ShopsController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = Shop.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   Shop.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/admin/users_controller.rb
module Admin
  class UsersController < Admin::ApplicationController
    # To customize the behavior of this controller,
    # simply overwrite any of the RESTful actions. For example:
    #
    # def index
    #   super
    #   @resources = User.all.paginate(10, params[:page])
    # end

    # Define a custom finder by overriding the `find_resource` method:
    # def find_resource(param)
    #   User.find_by!(slug: param)
    # end

    # See https://administrate-docs.herokuapp.com/customizing_controller_actions
    # for more information
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController

  def index
    @location = Location.new
    @shops = []
  end

  def find
    @location = Location.new location_param

    if @location.address
      latlng = Geocoder.coordinates(@location.address)

      if latlng && latlng.count == 2
        @location.lat = latlng.first
        @location.lng = latlng.last
      end
    end

    if @location.validate
      if @location.range.present?
        @shops = Shop.near( [@location.lat, @location.lng], @location.range, :units => :km)
      elsif @location.number.present?
        @shops = Shop.near( [@location.lat, @location.lng]).first(@location.number.to_i)
      end
    else
      @shops = []
    end

    render 'shops/index'
  end

  private

  def location_param
    params.require(:location).permit(:lat, :lng, :address, :number, :range)
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :admin_only, :except => :show

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    unless current_user.admin?
      unless @user == current_user
        redirect_to :back, :alert => "Access denied."
      end
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(secure_params)
      redirect_to users_path, :notice => "User updated."
    else
      redirect_to users_path, :alert => "Unable to update user."
    end
  end

  def destroy
    user = User.find(params[:id])
    user.destroy
    redirect_to users_path, :notice => "User deleted."
  end

  private

  def admin_only
    unless current_user.admin?
      redirect_to :back, :alert => "Access denied."
    end
  end

  def secure_params
    params.require(:user).permit(:role)
  end

end

app/controllers/visitors_controller.rb
class VisitorsController < ApplicationController
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shop_helper.rb
module ShopHelper
end

app/views/layouts/_messages.html.haml
-# Rails flash messages styled for Bootstrap 3.0
- flash.each do |name, msg|
  - if msg.is_a?(String)
    %div{:class => "alert alert-#{name.to_s == 'notice' ? 'success' : 'danger'}"}
      %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
      = content_tag :div, msg, :id => "flash_#{name}"

app/views/layouts/_nav_links_for_auth.html.erb
<% if user_signed_in? %>
  <li><%= link_to 'Edit account', edit_user_registration_path %></li>
  <li><%= link_to 'Sign out', destroy_user_session_path, :method=>'delete' %></li>
<% else %>
  <li><%= link_to 'Sign in', new_user_session_path %></li>
  <li><%= link_to 'Sign up', new_user_registration_path %></li>
<% end %>

app/views/layouts/_navigation.html.haml
-# navigation styled for Bootstrap 3.0
%nav.navbar.navbar-default.navbar-fixed-top
  .container
    .navbar-header
      %button.navbar-toggle{"data-target" => ".navbar-collapse", "data-toggle" => "collapse", :type => "button"}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar
      = link_to 'Home', root_path, class: 'navbar-brand'
    .collapse.navbar-collapse
      %ul.nav.navbar-nav
        = render 'layouts/navigation_links'

app/views/layouts/_navigation_links.html.haml
= link_to 'Find Stores!', shops_path, class: 'navbar-brand'

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:name => "viewport", :content => "width=device-width, initial-scale=1.0"}
    %title= content_for?(:title) ? yield(:title) : 'Shops List'
    %meta{:name => "description", :content => "#{content_for?(:description) ? yield(:description) : 'Shops List'}"}
    = stylesheet_link_tag 'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags
  %body
    %header
      = render 'layouts/navigation'
    %main{:role => "main"}
      = render 'layouts/messages'
      = yield

app/views/shops/_shop.html.haml
%td
  - if @location && @location.lat && @location.lng
    = "#{shop.distance_from( [@location.lat, @location.lng] ).round(1) } km"
  - else
    = 'N/A'
%td
  = "#{shop.name}"
%td
  = "#{shop.full_street_address}"
%td
  = "0#{shop.phone}"

app/views/shops/find.html.haml
.container
 NOPE

app/views/shops/index.html.haml
.container
  = simple_form_for @location, url: '/shops/find' do |f|

    %h4.text-center{ style: "margin-top: 50px;" }
      Where are you right now ?

    .row.centered.text-center
      .col-md-5
        = f.input :lat, label: 'latitude', placeholder: 'ex: 48.85'
        = f.input :lng, label: 'longitude', placeholder: 'ex: 2.31'
      .col-md-2
        %br
        %br
        %br
        %h5
          OR
      .col-md-5
        = f.input :address, label: 'address', placeholder: 'ex: 119 avenue d\'italie, Paris'

    %h4.text-center{ style: "margin-top: 50px;" }
      Choose your filter

    .row.centered.text-center
      .col-md-5
        = f.input :number, label: 'X closest shops', placeholder: 'ex: 16'
      .col-md-2
        %br
        %h5
          OR
      .col-md-5
        = f.input :range, label: 'Shops in X km range', placeholder: 'ex: 5'
    .row{ style: "margin-top: 50px;" }
      = f.submit 'Find Stores!', class: 'btn btn-lg btn-success center-block'


.container{ style: "margin-top: 50px;" }
  %hr.text-center{ style: "width: 100%; color: black; height: 1px; background-color:grey;" }
  .row
    %h3.text-center
      = "#{@shops.map.count} shops found"
  .row
    %br
    %table.table.table-striped.table-bordered
      %thead
        %td Distance
        %td Name
        %td Addresse
        %td Phone
      %tbody
        - @shops.each do |shop|
          %tr
            = render shop

app/views/users/_user.html.erb
<td>
  <%= link_to user.email, user %>
</td>
<td>
  <%= form_for(user) do |f| %>
    <%= f.select(:role, User.roles.keys.map {|role| [role.titleize,role]}) %>
    <%= f.submit 'Change Role', :class => 'button-xs' %>
  <% end %>
</td>
<td>
  <%= link_to("Delete user", user_path(user), :data => { :confirm => "Are you sure?" }, :method => :delete, :class => 'button-xs') unless user == current_user %>
</td>

app/views/users/index.html.erb
<div class="container">
  <div class="row">
    <h3>Users</h3>
    <div class="column">
      <table class="table">
        <tbody>
          <% @users.each do |user| %>
            <tr>
              <%= render user %>
            </tr>
          <% end %>
        </tbody>
      </table>
    </div>
  </div>
</div>

app/views/users/show.html.erb
<h3>User</h3>
<p>Email: <%= @user.email if @user.email %></p>

app/views/visitors/index.html.erb
<div id="wrapper">

  <!-- Page Content -->
  <div id="page-content-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-lg-12">
          <h3>Shops List by Flavien Hello</h3>
          <p>This site let you administrate a list of shops.</p>
          <p>Those shops are displayed to any user and are filterable by geolocalisation.</p>
        </div>

        <div class="container-fluid">
          <div class="row">
            <div class="col-md-offset-2 col-md-4" style="margin-top: 40px;">
              <%= link_to 'Find Stores!', shops_path, class: 'btn btn-lg btn-success center-block' %>
            </div>

          </div>
        </div>
      </div>
    </div>
  </div>
  <!-- /#page-content-wrapper -->

</div>
<!-- /#wrapper -->

<!-- Menu Toggle Script -->
<script>
    $("#menu-toggle").click(function(e) {
        e.preventDefault();
        $("#wrapper").toggleClass("toggled");
    });
</script>